webproject/blog/urls.py
from django.conf.urls import url,include,patterns
from blog import views

urlpatterns = patterns('',
                       # 인덱스 페이지 (블로그 메인 페이지)
                       url(r'^$',views.Index.as_view(),name='index'),
                       url(r'^category/(?P<name>[a-zA-z0-9가-힣]+)/$',views.CategoryList,name='Category'),
                       url(r'^tag/(?P<name>[a-zA-z0-9가-힣]+)/$',views.TagList,name='Tag'),
                       url(r'^post/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='PostDetail'),
                       )

webproject/everpython/urls.py
from django.conf.urls import url,include,patterns
from django.conf import settings
from django.contrib import admin
from jet.dashboard.dashboard_modules import google_analytics_views
urlpatterns = patterns('',
    url(r'^',include('blog.urls',namespace="blog")),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
                       )


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

webproject/templates/module/sidebarmenu.html
<a class="item" href="{% url 'blog:index' %}">
    <h3 class="ui inverted header"><i class="terminal icon"></i>EVERYPYTHON</h3>
</a>
<a class="active gray item" href="{% url 'blog:index' %}">대문<i class="home icon"></i></a>
{# 기능 구현 완료시 주석해제 하기 <a class="item">전체글<i class="folder icon"></i></a> #}
<a class="item">카테고리<i class="folder icon"></i></a>
{% if categorytree %}
    {% for group in categorytree %}
        {# 그룹에서 가장 앞의 카테고리를 1차 카테고리로 분류 #}
        {% with c1=group.0 %}
            {% with c_level=c1.0 c_name=c1.1 c_countpost=c1.2 %}
                {% if group|length == 1 %}
                    <a class="item c1" href="{% url 'blog:Category' c_name %}">
                        <div class="ui tiny label">{{ c_countpost|default_if_none:0 }}</div>
                        <i class="folder icon"></i>{{ c_name }}
                    </a>
                {% else %}
                    {% with under_c=group|slice:'1:' %}
                        {# 1차 카테고리 #}
                        <a class="item c1" href="{% url 'blog:Category' c_name %}">
                            <div class="ui tiny label">{{ c_countpost|default_if_none:0 }}</div>
                            <i class="folder icon"></i>{{ c_name }}
                        </a>
                        <div class="undercategory item">
                            <div class="undercategory items">
                                {% for c_level,c_name,c_countpost in under_c %}
                                    {# 2차 카테고리 #}
                                    {% if c_level == 2 %}
                                        <a class="item c2" href="{% url 'blog:Category' c_name %}">
                                            <div class="ui tiny label">{{ c_countpost|default_if_none:0 }}</div>
                                            <i class="folder icon"></i>{{ c_name|truncatechars:13 }}
                                        </a>
                                        {# 3차 카테고리 #}
                                    {% elif c_level == 3 %}
                                        <a class="item c3" href="{% url 'blog:Category' c_name %}">
                                            <div class="ui tiny label">{{ c_countpost|default_if_none:0 }}</div>
                                            <i class="folder icon"></i>{{ c_name|truncatechars:13 }}
                                        </a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endwith %}
                {% endif %}
            {% endwith %}
        {% endwith %}
    {% endfor %}
{% else %}
    <a class="item">카테고리가 없습니다</a>
{% endif %}
<a class="item" href="/admin/">
    관리자
</a>