webproject/blog/urls.py
from django.conf.urls import url,include,patterns
from blog import views

urlpatterns = patterns('',
                       # 인덱스 페이지 (블로그 메인 페이지)
                       url(r'^$',views.Index.as_view(),name='index'),
                       url(r'^category/(?P<name>[a-zA-z0-9가-힣]+)/$',views.CategoryList,name='Category'),
                       url(r'^tag/(?P<name>[a-zA-z0-9가-힣]+)/$',views.TagList,name='Tag'),
                       url(r'^post/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='PostDetail'),
                       )

webproject/everpython/urls.py
from django.conf.urls import url,include,patterns
from django.conf import settings
from django.contrib import admin
from jet.dashboard.dashboard_modules import google_analytics_views
urlpatterns = patterns('',
    url(r'^',include('blog.urls',namespace="blog")),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
                       )


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

webproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from taggit.models import Tag
from hitcount.models import HitCountMixin, HitCount
from django.db.models.query import QuerySet
from django.db.models import Q, Count, Sum, Case, When, IntegerField
# 오류 발생용
from django.core.exceptions import ValidationError

# hticount 필드 연결용
from django.contrib.contenttypes.fields import GenericRelation


# Create your models here.


# 카테고리 목록 매니저
class CategoryMixin(object):
    """
    카테고리 정보를 추출해준다
    """

    def root_category(self):
        """
        최상단 카테고리를 추출한다
        :return:
        """
        return self.filter(level=1)

    def under_list(self, c):
        """ 입력받은 카테고리에 대한 하위카테고리 목록을 쿼리셋으로 돌려준 """
        order = "ordercategory__order_num"
        if c.level == 1:
            c2 = Category.objects.filter(parent=c)
            under_C = Category.objects.filter(Q(name=c) | Q(parent=c) | Q(parent__in=c2)).order_by(order)
        elif c.level == 2:
            under_C = Category.objects.filter(Q(name=c) | Q(parent=c)).order_by(order)
        elif c.level == 3:
            under_C = c
        return under_C

    def navi_bar(self):
        """
        네비게이션 바에 뿌려줄 카테고리 목록을 만들어주는 함수
        전체 카테고리에 대한 정보를 추출하여 뷰와 템플릿에서 처리하기 쉽도록 아래의 구조로 바꿔준다.
        -- return값 구조
            카테고리 리스트엔 각 최상위 카테고리와 그 하위 카테고리 정보가 담긴 리스트들로 구성되있다.
            예시 : [ [(카테고리1),(카테고리1-1),..], [(카테고리2),(카테고리2-1),...] ]
        """
        c_list = Category.objects.all().order_by("ordercategory__order_num")
        # 발행된 포스트만 계수하기 위한 ORM : 발행=1, 미발행=0으로 하여 총 합을 구한다.
        postcount = Sum(Case(When(post__publish=True, then=1), default=0, output_field=IntegerField()))
        #  전체 카테고리의 정보를 튜플로 추출한다.
        c_info = c_list.annotate(count_posts=postcount).values_list('level', 'name', 'count_posts')

        # 카테고리가 없을경우 처리
        if c_info:
            # 카테고리 정보를 뷰와 템플릿에서 처리하기 쉽도록 구조를 변경한다.
            category_tree = []
            c_underlist = []
            for c in c_info:
                if c[0] == 1:  # 최상위 카테고리
                    if c_underlist:  # 이전 최상위 카테고리 목록이 존재할 경우 카테고리 목록 초기화
                        category_tree.append(c_underlist)
                        c_underlist = []
                    c_underlist.append(c)
                else:  # 차상위 카테고리
                    c_underlist.append(c)
            category_tree.append(c_underlist)  # 마지막 촤상위 카테고리 목록 추가
        else:
            # 아무런 카테고리가 존재하지 않을 경우(블로그 첫 설치했을떄)를 템플릿에서 분기하기 위해 None값으로 반환함
            category_tree = None

        return category_tree

    def categorys_post(self, c):
        posts = Category.tree.under_list(c)
        return posts


class CategoryQuerySets(QuerySet, CategoryMixin):
    pass


class CategoryManager(models.Manager, CategoryMixin):
    def get_query_set(self):
        return CategoryQuerySets(self.model, using=self._db)


# 카테고리 모델
class Category(models.Model):
    """
    포스트 카테고리 - 추가,업데이트,삭제 할때마다 카테고리 순서 모델을 갱신시킨다.
    정규화된 카테고리 이동은 아직 지원 안함, 카테고리 이동시 주의 필
    level = 카테고리 단계로 총 3단계까지 있음
    name = 카테고리 명
    under_category = 관계된 카테고리
    """

    parent = models.ForeignKey('self', limit_choices_to=Q(level=1) | Q(level=2), on_delete=models.CASCADE, blank=True,
                               null=True, help_text="상위 카테고리를 정해주세요,미지정시 최상위 카테고리가 됩니", verbose_name='상위 카테고리')
    name = models.CharField(max_length=15, unique=True, help_text="카테고리 이름을 입력하세요", verbose_name='이름')
    level = models.IntegerField(choices=[(1, '최상위 카테고리'), (2, '2차 카테고리'), (3, '3차 카테고리')], blank=True,
                                verbose_name='단계')
    objects = models.Manager()
    # 카테고리 매니저
    tree = CategoryManager()

    def __str__(self):
        return self.name

    def clean(self):
        # 부모 카테고리 검증
        if self.parent:
            if self.parent_id == self.id:
                raise ValidationError('자기자신을 상위카테고리로 지정할수 없습니다.', code='invalid')

    def save(self, *args, **kwargs):
        if self.parent:
            if self.parent_id == self.id:
                raise ValidationError('자기자신을 상위카테고리로 지정할수 없습니다.', code='invalid')
        # 카테고리 레벨 자동 지정
        if not self.parent:
            self.level = 1
        elif self.parent.level == 1:
            self.level = 2
        elif self.parent.level == 2:
            self.level = 3
        super(Category, self).save(*args, **kwargs)
        # 카테고리 순서 모델을 갱신
        OrderCategory.order.reset_order()

    def delete(self, *args, **kwargs):
        super(Category, self).delete(*args, **kwargs)
        # 카테고리 순서 모델을 갱신
        OrderCategory.order.reset_order()


# 카테고리 정렬 매니저
class OrderMixin(object):
    """
    카테고리 순서 번호를 갱신한다.
    """

    def reset_order(self):
        OrderCategory.objects.all().delete()
        loop_c1 = 0
        for c1 in Category.tree.root_category():
            loop_c1 += 1
            c1obj = OrderCategory(c_pk_id=c1.id, order_num=10000 * loop_c1)
            c1obj.save()
            c2s = Category.objects.filter(parent_id=c1.id)
            if c2s.exists():
                loop_c2 = 0
                for c2 in c2s:
                    loop_c2 += 1
                    c2obj = OrderCategory(c_pk_id=c2.id, order_num=c1obj.order_num + 100 * loop_c2)
                    c2obj.save()
                    c3s = Category.objects.filter(parent_id=c2.id)
                    if c3s.exists():
                        loop_c3 = 0
                        for c3 in c3s:
                            loop_c3 += 1
                            c3obj = OrderCategory(c_pk_id=c3.id, order_num=c2obj.order_num + 1 * loop_c3)
                            c3obj.save()
                    else:
                        continue
            else:
                continue


class OrderQuerySets(QuerySet, OrderMixin):
    pass


class OrderManager(models.Manager, OrderMixin):
    def get_query_set(self):
        return OrderQuerySets(self.model, using=self._db)


# 카테고리 정렬 모델
class OrderCategory(models.Model):
    """카테고리 순서 갱신용 모델"""
    c_pk = models.OneToOneField('Category', unique=True)
    order_num = models.IntegerField()
    objects = models.Manager()
    order = OrderManager()

    def __str__(self):
        return self.c_pk.name


# 포스트 발행 관리 매니저
class PublishMixin(object):
    """
    포스트 발행 관리를 위한 믹스인
    """

    def publish(self):
        """발행된 포스트 목록"""
        return self.filter(publish=True)

    def dreft(self):
        """미발행 포스트(초안) 목록"""
        return self.filter(publish=False)

    def posts_info(self, post_queryset):
        """
        포스트 목록 쿼리셋을 받아 포스트목록에 보여줄 정보를 취합하여 list로 넘겨준다
        list에 담겨지는 포스 정보의 구조 : (pk,category,created_date,hitcounts,title,description(없을시엔 contnent의 100자까지로 대체),tags)
        """
        posts = list(post_queryset.select_related('category').prefetch_related('tag'))
        info_list = [(
                     p.pk, p.category.name, p.create_date, p.title, p.description if p.description else p.content[:100],
                     [t.name for t in p.tag.all()]) for p in posts]
        return info_list


class PublishQuerySets(QuerySet, PublishMixin):
    pass


class PublishManager(models.Manager, PublishMixin):
    def get_query_set(self):
        return PublishQuerySets(self.model, using=self._db)


# 포스트 모델
class Post(models.Model, HitCountMixin):
    """
    블로그 포스트 모델
    """
    category = models.ForeignKey('Category', blank=True, null=True, verbose_name='카테고리')
    title = models.CharField(verbose_name='제목', max_length=60)
    author = models.ForeignKey(User, verbose_name='글쓴이')
    description = models.CharField(verbose_name='요약', max_length=160, blank=True, null=True,
                                   help_text="포스트를 sns에 공유하거나 검색에서 노출될 포스트에 대한 요약입니다.")
    content = models.TextField(verbose_name='내용')
    markdown = models.BooleanField(verbose_name="마크다운", default=False, blank=True, help_text="마크다운 형식으로 글을 작성하려면 체크하세")
    tag = TaggableManager()
    create_date = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    edit_date = models.DateTimeField(verbose_name='수정일', auto_now=True)
    publish = models.BooleanField(verbose_name='발행여부', default=False,
                                  help_text="포스트 발행시 외부에 포스트가 공개됩니다. 만약 발행하지 않는다면 작성자만 해당 포스트를 볼 수 있습니다.")

    # hitcount 모듈과 연동
    posthits = GenericRelation(HitCount, related_query_name='post', object_id_field='object_pk')

    objects = models.Manager()
    # 발행 포스트 관리 매니저
    published = PublishManager()

    def __str__(self):
        return self.title

webproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.views.generic import View
from .models import Category, Post
from django.conf import settings
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from hitcount.models import HitCount
from taggit.models import Tag
from hitcount.views import HitCountDetailView


def base_context():
    """
    블로그에 기본적으로 들어갈 context을 넘겨주는 함수. (사이드바,구글 태그 매니저)
    context.update(base_context())  통해 각페이지 context에 카테고리 정보를 넘겨준다
    :return:
    """
    gtm = getattr(settings,'GTM_STATE')
    categorytree = Category.tree.navi_bar()
    context_dic = {'categorytree': categorytree, 'gtm': gtm}
    return context_dic

def makepage(request,post_list,viewnum=8):
    """
    포스트목록을 페이지 처리를 하여 포스트목록을 반환한다.
    :param request: 처리할 요청의 request/ page 정보값을 알아낼때 사용
    :param post_list: 포스트 목록에 뿌려질 정보 모음
    :param viewnum: 한 페이지에 보여줄 포스트 수
    :return: 해당 페이지에 맞는 포스트 목록
    """
    # 페이지 번호
    page = request.GET.get('page')
    # 넘겨받은 자료를 페이징 처리
    paginator = Paginator(post_list, viewnum)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return posts

class Index(View):
    def get(self, request, data=None):
        # index 페이지에 넘겨줄 컨텐츠 context
        tags = Tag.objects.all().filter(post__publish=True).annotate(Count('post')).values_list('name', 'post__count')
        publish = Post.published.publish()
        # 최신글 목록 추출
        q_newposts = publish.order_by('-create_date')[:2]
        newposts = Post.published.posts_info(q_newposts)

        # 인기글 목록 추출
        q_starposts = publish.order_by('-posthits__hits')[:3]
        starposts = Post.published.posts_info(q_starposts)


        # 사이드바에 필요한 context를 합쳐줌
        context = {'tags': tags, 'newposts': newposts, 'starposts': starposts}
        context.update(base_context())
        data = render_to_string("blog/index.html", context, request=request)
        return HttpResponse(data)


def CategoryList(request, name):
    c = get_object_or_404(Category, name=name)
    categorys = Category.tree.under_list(c)
    if c.level == 3:
        post_queryset = Post.published.publish().filter(category=c).order_by('-id')
    else:
        categorys = Category.tree.under_list(c)
        post_queryset = Post.published.publish().filter(category__in=categorys).order_by('-id')
    post_list = Post.published.posts_info(post_queryset)

    #포스트 목록 페이지 처리
    posts = makepage(request,post_list,viewnum=3)

    context = {"posts": posts, "name": c.name}
    # 사이드바에 필요한 context를 합쳐줌
    context.update(base_context())
    return render(request, 'blog/category.html', context)


def TagList(request, name):
    tag = Tag.objects.get(name=name)
    # 태그에 속한 모든 포스트를 찾는다
    post_queryset = Post.published.publish().filter(tag__name__in=[tag]).order_by('-id')
    post_list = Post.published.posts_info(post_queryset)

    #포스트 목록 페이지 처리
    posts = makepage(request,post_list)

    context = {"posts": posts, "name": tag.name}
    # 사이드바에 필요한 context를 합쳐줌
    context.update(base_context())
    return render(request, 'blog/tag.html', context)


class PostDetail(HitCountDetailView):
    model = Post
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)

        context['shortname'] = getattr(settings, 'SHORTNAME')
        context['og'] = getattr(settings,'OG_TAG')
        if getattr(settings,'AD_STATE'):
            context['ad'] = getattr(settings,'AD_STATE')

        # 사이드바에 필요한 context를 합쳐줌
        context.update(base_context())
        return context

webproject/blog/templates/blog/module/label_tag.html
<a class="ui label" href="{% url 'blog:Tag' t_name %}">{{ t_name }}
    <div class="detail">{{ t_count }}</div>
</a>

webproject/blog/templates/blog/module/list_post.html
<div class="item">
    <div class="content">
        <div class="meta">
            <a class="ui blue ribbon label" href="{% url 'blog:Category' category %}"><i class="folder icon"></i> &nbsp;{{ category }}</a>
            <div class="ui tiny label">
                <i class="calendar icon"></i>&nbsp;{{ created_date|date:"Y M d" }}
                <div class="detail">{{ created_date|timesince }} 전</div>
            </div>
            {% comment %} 추후 댓글수를 보여주는게 구현되면 수정하자.
            <a class="ui tiny label">
                <i class="comments icon"></i>&nbsp;&nbsp;&nbsp;{{ hits }}
            </a>
            {% endcomment %}

        </div>
        <a class="header" href="{% url 'blog:PostDetail' pk %}">{{ title }}</a>
        <div class="description">
            <p>{{ description|striptags }}</p>
        </div>
        <div class="extra">
            <div class="ui right floated mini teal tag labels">
                <i class="ui large teal tags icon"></i>
                {% for tag in tags %}
                <a class="ui label" href="{% url 'blog:Tag' tag %}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

webproject/blog/templates/blog/module/og_postdetail.html
    {% if og.name %}<meta property="og:site_name"          content="{{ og.name }}" />{% endif %}
    <meta property="og:url"                content="{{request.build_absolute_uri}}" />
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="{{ object.title }}" />
    <meta property="og:description"        content="{{ object.description }}" />
    {% if og.img %}<meta property="og:image"              content="{{ og.img }}" />{% endif %}
    {% if og.img_type %}<meta property="og:image:type"       content="{{ og.img_type }}"/>{% endif %}
    {% if og.img_width %}<meta property="og:image:width"      content="{{ og.img_width }}"/>{% endif %}
    {% if og.img_height %}<meta property="og:image:height"     content="{{ og.img_height }}"/>{% endif %}
    {% if og.local %}<meta property="og:locale"             content="{{ og.local }}" />{% endif %}

webproject/blog/templates/blog/module/pagination_posts.html
{% if posts and posts.paginator.page_range|length != 1 %}
    <div class="centered row">
        <div class="one colum">
            <div class="ui center buttons">
                {% if posts.has_previous %}
                    <a class="ui icon button" href="?page={{ posts.previous_page_number }}">
                        <i class="left chevron icon"></i>
                    </a>
                {% endif %}
                {% for pg in posts.paginator.page_range %}
                    {% if posts.number == pg %}
                        <a class="ui active button" href="?page={{ pg }}">{{ pg }}</a>
                    {% else %}
                        <a class="ui button" href="?page={{ pg }}">{{ pg }}</a>
                    {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                    <a class="ui icon button" href="?page={{ posts.next_page_number }}">
                        <i class="right chevron icon"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}